# Generated by Django 2.1.7 on 2019-03-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='event',
        ),
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='event',
            name='parent',
        ),
        migrations.AddField(
            model_name='event',
            name='childs',
            field=models.ManyToManyField(to='main_app.Child'),
        ),
        migrations.AlterField(
            model_name='child',
            name='food_allergy',
            field=models.CharField(choices=[('M', 'Milk'), ('E', 'Eggs'), ('P', 'Peanuts'), ('T', 'Treenuts'), ('S', 'Soy'), ('W', 'Wheat'), ('F', 'Fish'), ('L', 'Shellfish')], default='M', max_length=1),
        ),
    ]
